server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ECommerceDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true